- name : Playbook_test
  hosts: node1
  remote_user: vagrant
  tasks:
  - name: vider repo
    shell: " rm /home/vagrant/AppFlask -rf"
    become: 'yes'
  - name: installation python & outils
    apt:
     name:
        - python3-pip
        - python3
        - curl
        - ca-certificates
        - software-properties-common
        - lsb-release
        - gnupg
        - libseccomp2
        - build-essential
        - apt-transport-https
     state: latest
    become: 'yes'
  - name: clone git 
    git: 
      repo: https://github.com/SophieDevops31/application_2_projet.git
      dest: /home/vagrant/AppFlask
      version: master 
      clone: yes
      update: no
  - name: docker compose
    shell: "cd AppFlask; sudo docker compose down; sudo docker compose up -d"
    become: 'yes'
