- name : Playbook_test
  hosts: node1
  remote_user: vagrant
  tasks:
  - name: vider repo
    shell: " rm /home/vagrant/AppFlask -rf"
    become: 'yes'
  - name: installation python & outils
    apt:
     name:
        - python3-pip
        - python3
        - curl
        - ca-certificates
        - software-properties-common
        - lsb-release
        - gnupg
        - libseccomp2
        - build-essential
        - apt-transport-https
     state: latest
    become: 'yes'
  - name: Add Docker GPG apt Key
    apt_key:
       url: https://download.docker.com/linux/debian/gpg
       state: present
    become: 'yes'
  - name: Add Docker Repository
    shell: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" '
    become: 'yes'
  - name: 
    shell: "curl -O https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/containerd.io_1.4.3-1_amd64.deb"
    become: 'yes'
  - name: clone git 
    git: 
      repo: https://github.com/SophieDevops31/application_2_projet.git
      dest: /home/vagrant/AppFlask
      version: master 
      clone: yes
      update: no
  - name: docker compose
    shell: "cd AppFlask; sudo docker compose down; sudo docker compose up -d"
    become: 'yes'
